# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Author.destroy_all
Book.destroy_all

holly = Author.create(name: "Holly Black", bio: "Holly Black née Riggenbach is an American writer and editor best known for The Spiderwick Chronicles, a series of children's fantasy books she created with writer and illustrator Tony DiTerlizzi, and a trilogy of Young Adult novels officially called the Modern Faerie Tales trilogy.")
john = Author.create(name: "John Green", bio: "John Michael Green was born on August 24, 1977, to Mike and Sydney Green in Indianapolis. He received his early education from Lake Highland Preparatory School and Indian Springs School. His experience of school was similar to other social outcasts who get bullied by arrogant people.")
clare = Author.create(name: "Cassandra Clare", bio: "Classandra Clare is a notable American young adult novel writer. She is famous for her paranormal YA series The Mortal Instruments. She earned numerous awards and prizes for her debut novel. ")
suzanne = Author.create(name: "Suzanne Collins", bio: "The youngest of four children, Suzanne Collins was born on August 10, 1962, in Hartford, Connecticut. The daughter of an Air Force officer, Collins moved a considerable amount during her childhood, living in places like New York City and Brussels. For the Collins family, history was an immensely important topic.")
ann = Author.create(name: "Ann Brashares", bio: "Ann Brashares is an American young adult novelist. She is best known as the author of The Sisterhood of the Traveling Pants series.")
roald = Author.create(name: "Roald Dahl", bio: "Roald Dahl was born September 13, 1916, in Llandaff, South Wales, United Kingdom, to Norwegian parents. He spent his childhood summers visiting his grandparents in Oslo, Norway. ... After his father died when Dahl was four, his mother followed her late husband's wish that Dahl be sent to English schools.")
rowling = Author.create(name: "J.K. Rowling", bio: "Joanne Rowling was born on 31st July 1965 at Yate General Hospital near Bristol, and grew up in Gloucestershire in England and in Chepstow, Gwent, in south-east Wales. ... Anne was diagnosed with multiple sclerosis when Jo was a teenager and died in 1990, before the Harry Potter books were published.")


Book.create(title: "Heart of the Moors", author: holly , purchase_url: "https://www.amazon.com/Heart-Moors-Original-Maleficent-Mistress-ebook/dp/B07WC674TL", description: "From New York Times bestselling author Holly Black comes a captivating original novel set between Disney's Maleficent and Maleficent: Mistress of Evil, in which newly-queened Aurora struggles to be the best leader to both the humans and Fair Folk under her reign; her beau, Prince Phillip, longs to get to know Aurora and her kingdom better; and Maleficent has trouble letting go of the past." , image_url:"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1565242796l/44782217.jpg", category: "Fantasy" )
Book.create(title: "The Fault In Our Stars", author: john, purchase_url: "https://www.amazon.com/Fault-Our-Stars-John-Green/dp/014242417X/ref=sr_1_3?crid=2T2HS0G6FV81Z&keywords=the+fault+in+our+stars+book&qid=1569939920&s=gateway&sprefix=the+faul%2Caps%2C143&sr=8-3", description: "The Fault in Our Stars, published in January 2012, is the sixth novel by author John Green. The title is inspired by Act 1, Scene 2 of Shakespeare's play Julius Caesar, in which the nobleman Cassius says to Brutus: 'The fault, dear Brutus, is not in our stars, / But in ourselves, that we are underlings.'" , image_url: "https://images-na.ssl-images-amazon.com/images/I/81yAo5ElQlL.jpg", category: "Coming of Age")
Book.create(title: "City of Bones", author: clare, purchase_url: "https://www.amazon.com/gp/product/B0013TXA5Y/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i0", description: "Exotic and gritty, exhilarating and utterly gripping, Cassandra Clare's ferociously entertaining fantasy takes readers on a wild ride that they will never want to end.", image_url: "https://images-na.ssl-images-amazon.com/images/I/512qJxcvPzL.jpg" , category: "Fantasy" )
Book.create(title: "The Hunger Games", author: suzanne, purchase_url: "https://www.amazon.com/The-Hunger-Games-Special-Edition/dp/B07HHJ7669/ref=sr_1_1?keywords=the+hunger+games+book+1&qid=1569940214&s=gateway&sr=8-1", description: "Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to death before - and survival, for her, is second nature. Still, if she is to win, she will have to start making choices that weigh survival against humanity and life against love.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51vOc7NtICL._SX342_.jpg", category: "Science Fiction")
Book.create(title: "Sisterhood of the Traveling Pants", author: ann, purchase_url: "https://www.amazon.com/Sisterhood-Traveling-Pants-Book-ebook/dp/B000FBFNBA/ref=sr_1_1?crid=EYWQ199OBPNB&keywords=sisterhood+of+the+traveling+pants&qid=1569940407&s=digital-text&sprefix=sisterhood+of+th%2Cdigital-text%2C139&sr=1-1", description: "The first novel in the wildly popular #1 New York Times bestselling Sisterhood of the Traveling Pants series, from the author of The Whole Thing Together and The Here and Now.
  Some friends just fit together.
  Once there was a pair of pants. Just an ordinary pair of jeans. But these pants, the Traveling Pants, went on to do great things. This is the story of the four friends—Lena, Tibby, Bridget, and Carmen—who made it possible.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51XPnliIcSL._SX331_BO1,204,203,200_.jpg", category: "Coming of Age")
Book.create(title: "Charlie and the Chocolate Factory", author: roald, purchase_url: "https://www.amazon.com/Charlie-Chocolate-Factory-Roald-Dahl/dp/0425287661/ref=sr_1_1?keywords=roald+dahl+charlie+and+the+chocolate+factory+book&qid=1569940459&s=gateway&sr=8-1", description: "Willy Wonka's famous chocolate factory is opening at last! But only five lucky children will be allowed inside. And the winners are: Augustus Gloop, an enormous boy whose hobby is eating; Veruca Salt, a spoiled-rotten brat whose parents are wrapped around her little finger; Violet Beauregarde, a dim-witted gum-chewer with the fastest jaws around; Mike Teavee, a toy pistol-toting gangster-in-training who is obsessed with television; and Charlie Bucket, Our Hero, a boy who is honest and kind, brave and true, and good and ready for the wildest time of his life!", image_url: "https://images-na.ssl-images-amazon.com/images/I/417siQLulZL._SX337_BO1,204,203,200_.jpg", category: "Fantasy")
Book.create(title: "Harry Potter and the Goblet of Fire", author: rowling, purchase_url: "https://www.amazon.com/dp/B0192CTMUU/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1", description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!", image_url: "https://images-na.ssl-images-amazon.com/images/I/51WR45IjfSL.jpg", category: "Fantasy")
