# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Author.destroy_all
Book.destroy_all

holly = Author.create(name: "Holly Black", bio: "Holly Black née Riggenbach is an American writer and editor best known for The Spiderwick Chronicles, a series of children's fantasy books she created with writer and illustrator Tony DiTerlizzi, and a trilogy of Young Adult novels officially called the Modern Faerie Tales trilogy.")
john = Author.create(name: "John Green", bio: "John Michael Green was born on August 24, 1977, to Mike and Sydney Green in Indianapolis. He received his early education from Lake Highland Preparatory School and Indian Springs School. His experience of school was similar to other social outcasts who get bullied by arrogant people.")
clare = Author.create(name: "Cassandra Clare", bio: "Classandra Clare is a notable American young adult novel writer. She is famous for her paranormal YA series The Mortal Instruments. She earned numerous awards and prizes for her debut novel. ")
suzanne = Author.create(name: "Suzanne Collins", bio: "The youngest of four children, Suzanne Collins was born on August 10, 1962, in Hartford, Connecticut. The daughter of an Air Force officer, Collins moved a considerable amount during her childhood, living in places like New York City and Brussels. For the Collins family, history was an immensely important topic.")
ann = Author.create(name: "Ann Brashares", bio: "Ann Brashares is an American young adult novelist. She is best known as the author of The Sisterhood of the Traveling Pants series.")
roald = Author.create(name: "Roald Dahl", bio: "Roald Dahl was born September 13, 1916, in Llandaff, South Wales, United Kingdom, to Norwegian parents. He spent his childhood summers visiting his grandparents in Oslo, Norway. ... After his father died when Dahl was four, his mother followed her late husband's wish that Dahl be sent to English schools.")
rowling = Author.create(name: "J.K. Rowling", bio: "Joanne Rowling was born on 31st July 1965 at Yate General Hospital near Bristol, and grew up in Gloucestershire in England and in Chepstow, Gwent, in south-east Wales. ... Anne was diagnosed with multiple sclerosis when Jo was a teenager and died in 1990, before the Harry Potter books were published.")

a_thomas = Author.create(name: "Angie Thomas", bio: "Angie Thomas was born, raised, and still lives in Jackson, Mississippi. A former teen rapper, she holds a BFA in creative writing from Belhaven University. Her award-winning, acclaimed debut novel, The Hate You Give, is a #1 New York Times bestseller and major motion picture from Fox 2000, starring Amandla Stenberg and directed by George Tillman, Jr. Her second novel, On The Come Up, is on sale now.")
m_lu = Author.create(name: "Marie Lu", bio: "Marie Lu was born in 1984, in China. She left Beijing for the States in 1989 and went to college at the University of Southern California. Lu is the author of the New York Times bestselling novels Legend and Prodigy. She graduated from the University of Southern California and jumped into the video game industry, working for Disney Interactive Studios as a Flash artist. Now a full-time writer, she spends her spare time reading, drawing, playing Assassin's Creed, and getting stuck in traffic. She currently lives in Los Angeles (see above: traffic) with her fiancé, one Chihuahua mix, and two Pembroke Welsh Corgis.")
m_meyer = Author.create(name: "Marissa Meyer", bio: "Marissa Meyer is an American young adult novelist. Meyer’s debut novel, Cinder (2012), was a New York Times bestseller, and is the first of her Lunar Chronicles series which includes Scarlet (2013), Cress (2014), Winter (2015), and Fairest (2015). In 2013 she received a contract with Feiwel and Friends for a young adult series featuring the Queen of Hearts from Alice in Wonderland. The first book, Heartless, of the two book series, has a release date of February 2016.")
d_levithan = Author.create(name: "David Levithan", bio: "David Levithan finds it downright baffling to write about himself, which is why he's considering it somewhat cruel and usual to have to write this brief bio.  The factual approach (born '72, Brown '94, book '03) seems a bit dry, while the emotional landscape (happy childhood, happy adolescence - give or take a few poems - and happy adulthood so far) sounds horribly well-adjusted.  The only addiction he's ever had was a brief spiral into the arms of diet Dr Pepper, unless you count My So-Called Life episodes as a drug.  He is evangelical in his musical beliefs and deathly afraid that his bio will end up sounding like the final paragraph in an on-line dating ad.")
j_woodson = Author.create(name: "Jacqueline Woodson", bio: "Jacqueline Woodson is an award-winning author of young adult books. Raised and educated in Greenville, South Carolina, and Brooklyn, New York, Woodson graduated from college with a B.A. in English, and then worked in New York City as a drama therapist for runaways and homeless children. She now writes full-time in Brooklyn. Woodson often writes about characters that feel out of place and the difficulties young people face. Woodson won a Newbery Honor in 2006 for Show Way. Locomotion was a National Book Award finalist and won a Coretta Scott King Honor in 2004. Woodson also won a Corretta Scott King Honor in 2001 and the Los Angeles Times Book Prize for Miracle's Boys, which was made into a mini-series. In 2006, she won the Margaret A. Edwards Award for lifetime achievement in writing for young adults from the Young Adult Library Services Association.")
l_oliver = Author.create(name: "Lauren Oliver", bio: "Lauren Oliver is the author of the New York Times bestseller Before I Fall, a Publishers Weekly Best Book of the Year. Her thrilling second novel, Delirium, debuted on the New York Times bestseller list and is the first book in a trilogy. The second volume is Pandemonium (March 2012). Oliver is also the author of a luminous novel for younger readers, Liesl & Po. A graduate of the University of Chicago and the MFA program at New York University, Lauren is now a full-time writer and lives in Brooklyn, New York.")
l_bardugo = Author.create(name: "Leigh Bardugo", bio: "Leigh Bardugo is a #1 New York Times bestselling author of fantasy novels and the creator of the Grishaverse. With over 3 million copies sold worldwide, her Grishaverse spans the Shadow and Bone trilogy, the Six of Crows duology, The Language of Thorns, King of Scars―with more to come. Her other works include Wonder Woman: Warbringer and short stories that have appeared in The Best of Tor.com and the Best American Science Fiction & Fantasy. She lives in Los Angeles.")
l_taylor = Author.create(name: "Laini Taylor", bio: "Laini Taylor is the author of five novels including Days of Blood & Starlight, Daughter of Smoke & Bone, the Dreamdark books Blackbringer and Silksinger, and the National Book Award finalist Lips Touch: Three Times. She lives in Portland, Oregon with her husband, illustrator Jim Di Bartolo, and their daughter, Clementine.")


Book.create(title: "Heart of the Moors", author: holly , purchase_url: "https://www.amazon.com/Heart-Moors-Original-Maleficent-Mistress-ebook/dp/B07WC674TL", description: "From New York Times bestselling author Holly Black comes a captivating original novel set between Disney's Maleficent and Maleficent: Mistress of Evil, in which newly-queened Aurora struggles to be the best leader to both the humans and Fair Folk under her reign; her beau, Prince Phillip, longs to get to know Aurora and her kingdom better; and Maleficent has trouble letting go of the past." , image_url:"https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1565242796l/44782217.jpg", category: "Fantasy" )
Book.create(title: "The Fault In Our Stars", author: john, purchase_url: "https://www.amazon.com/Fault-Our-Stars-John-Green/dp/014242417X/ref=sr_1_3?crid=2T2HS0G6FV81Z&keywords=the+fault+in+our+stars+book&qid=1569939920&s=gateway&sprefix=the+faul%2Caps%2C143&sr=8-3", description: "The Fault in Our Stars, published in January 2012, is the sixth novel by author John Green. The title is inspired by Act 1, Scene 2 of Shakespeare's play Julius Caesar, in which the nobleman Cassius says to Brutus: 'The fault, dear Brutus, is not in our stars, / But in ourselves, that we are underlings.'" , image_url: "https://images-na.ssl-images-amazon.com/images/I/81yAo5ElQlL.jpg", category: "Coming of Age")
Book.create(title: "City of Bones", author: clare, purchase_url: "https://www.amazon.com/gp/product/B0013TXA5Y/ref=dbs_a_def_rwt_hsch_vapi_tkin_p1_i0", description: "Exotic and gritty, exhilarating and utterly gripping, Cassandra Clare's ferociously entertaining fantasy takes readers on a wild ride that they will never want to end.", image_url: "https://images-na.ssl-images-amazon.com/images/I/512qJxcvPzL.jpg" , category: "Fantasy" )
Book.create(title: "The Hunger Games", author: suzanne, purchase_url: "https://www.amazon.com/The-Hunger-Games-Special-Edition/dp/B07HHJ7669/ref=sr_1_1?keywords=the+hunger+games+book+1&qid=1569940214&s=gateway&sr=8-1", description: "Sixteen-year-old Katniss Everdeen regards it as a death sentence when she steps forward to take her sister's place in the Games. But Katniss has been close to death before - and survival, for her, is second nature. Still, if she is to win, she will have to start making choices that weigh survival against humanity and life against love.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51vOc7NtICL._SX342_.jpg", category: "Science Fiction")
Book.create(title: "Sisterhood of the Traveling Pants", author: ann, purchase_url: "https://www.amazon.com/Sisterhood-Traveling-Pants-Book-ebook/dp/B000FBFNBA/ref=sr_1_1?crid=EYWQ199OBPNB&keywords=sisterhood+of+the+traveling+pants&qid=1569940407&s=digital-text&sprefix=sisterhood+of+th%2Cdigital-text%2C139&sr=1-1", description: "The first novel in the wildly popular #1 New York Times bestselling Sisterhood of the Traveling Pants series, from the author of The Whole Thing Together and The Here and Now.
  Some friends just fit together.
  Once there was a pair of pants. Just an ordinary pair of jeans. But these pants, the Traveling Pants, went on to do great things. This is the story of the four friends—Lena, Tibby, Bridget, and Carmen—who made it possible.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51XPnliIcSL._SX331_BO1,204,203,200_.jpg", category: "Coming of Age")
Book.create(title: "Charlie and the Chocolate Factory", author: roald, purchase_url: "https://www.amazon.com/Charlie-Chocolate-Factory-Roald-Dahl/dp/0425287661/ref=sr_1_1?keywords=roald+dahl+charlie+and+the+chocolate+factory+book&qid=1569940459&s=gateway&sr=8-1", description: "Willy Wonka's famous chocolate factory is opening at last! But only five lucky children will be allowed inside. And the winners are: Augustus Gloop, an enormous boy whose hobby is eating; Veruca Salt, a spoiled-rotten brat whose parents are wrapped around her little finger; Violet Beauregarde, a dim-witted gum-chewer with the fastest jaws around; Mike Teavee, a toy pistol-toting gangster-in-training who is obsessed with television; and Charlie Bucket, Our Hero, a boy who is honest and kind, brave and true, and good and ready for the wildest time of his life!", image_url: "https://images-na.ssl-images-amazon.com/images/I/417siQLulZL._SX337_BO1,204,203,200_.jpg", category: "Fantasy")
Book.create(title: "Harry Potter and the Goblet of Fire", author: rowling, purchase_url: "https://www.amazon.com/dp/B0192CTMUU/ref=dp-kindle-redirect?_encoding=UTF8&btkr=1", description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!", image_url: "https://images-na.ssl-images-amazon.com/images/I/51WR45IjfSL.jpg", category: "Fantasy")

Book.create(title: "The Hate U Give", author: a_thomas, purchase_url: "https://www.amazon.com/Hate-U-Give-Collectors/dp/0062872346/ref=sr_1_2?keywords=the+hate+you+give&qid=1570111513&s=books&sr=1-2", description: "SIXTEEN-YEAR-OLD STARR CARTER moves between two worlds: the poor black neighborhood where she lives and the fancy suburban prep school she attends. The uneasy balance between these worlds is shattered when Starr witnesses the fatal shooting of her childhood best friend, Khalil, at the hands of a police officer. Khalil was unarmed. Soon afterward, Khalil’s death is a national headline. Some are calling him a thug, maybe even a drug dealer and a gangbanger. Starr’s best friend at school suggests he may have had it coming. When it becomes clear the police have little interest in investigating the incident, protesters take to the streets and Starr’s neighborhood becomes a war zone. What everyone wants to know is: What really went down that night? And the only person alive who can answer that is Starr. But what Starr does—or does not—say could destroy her community. It could also endanger her life.", image_url: "https://images-na.ssl-images-amazon.com/images/I/41NZXLBL9qL._SX329_BO1,204,203,200_.jpg", category: "Fiction")

Book.create(title: "Legend", author: m_lu, purchase_url: "https://www.amazon.com/Legend-Marie-Lu/dp/014242207X/ref=sr_1_1?keywords=legend&qid=1570112049&s=books&sr=1-1", description: "What was once the western United States is now home to the Republic, a nation perpetually at war with its neighbors. Born into an elite family in one of the Republic's wealthiest districts, fifteen-year-old June is a prodigy being groomed for success in the Republic's highest military circles. Born into the slums, fifteen-year-old Day is the country's most wanted criminal. But his motives may not be as malicious as they seem.", image_url: "https://images-na.ssl-images-amazon.com/images/I/61nV3oTC8vL._SX326_BO1,204,203,200_.jpg", category: "Science Fiction")

Book.create(title: "Renegades", author: m_meyer, purchase_url: "https://www.amazon.com/Renegades-Marissa-Meyer/dp/1250180635/ref=sr_1_4?crid=1T7L07C2882K7&keywords=marissa+meyer&qid=1570112311&s=books&sprefix=marissa+me%2Cstripbooks%2C153&sr=1-4", description: "Secret Identities. Extraordinary Powers. She wants vengeance. He wants justice. The Renegades are a syndicate of prodigies — humans with extraordinary abilities — who emerged from the ruins of a crumbled society and established peace and order where chaos reigned. As champions of justice, they remain a symbol of hope and courage to everyone... except the villains they once overthrew.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51SArX-622L._SX340_BO1,204,203,200_.jpg", category: "Fantasy")

Book.create(title: "Boy Meets Boy", author: d_levithan, purchase_url: "https://www.amazon.com/Boy-Meets-David-Levithan/dp/0375832998/ref=sr_1_1?crid=1HXCEV4H1V4S&keywords=boy+meets+boy&qid=1570112844&s=books&sprefix=Boy+meets+%2Cstripbooks%2C146&sr=1-1", description: "This is the story of Paul, a sophomore at a high school like no other: The cheerleaders ride Harleys, the homecoming queen used to be a guy named Daryl (she now prefers Infinite Darlene and is also the star quarterback), and the gay-straight alliance was formed to help the straight kids learn how to dance. When Paul meets Noah, he thinks he’s found the one his heart is made for. Until he blows it. The school bookie says the odds are 12-to-1 against him getting Noah back, but Paul’s not giving up without playing his love really loud. His best friend Joni might be drifting away, his other best friend Tony might be dealing with ultra-religious parents, and his ex-boyfriend Kyle might not be going away anytime soon, but sometimes everything needs to fall apart before it can really fit together right.", image_url: "https://images-na.ssl-images-amazon.com/images/I/31NdcBfqAfL._SX331_BO1,204,203,200_.jpg", category: "LGBT Friendly")

Book.create(title: "Locomotion", author: j_woodson, purchase_url: "https://www.amazon.com/Locomotion-Jacqueline-Woodson/dp/0142415529/ref=sr_1_5?keywords=jaqueline+woodson&qid=1570113174&s=books&sr=1-5", description: "When Lonnie was seven years old, his parents died in a fire. Now he's eleven, and he still misses them terribly. And he misses his little sister, Lili, who was put into a different foster home because 'not a lot of people want boys-not foster boys that ain't babies.' But Lonnie hasn't given up. His foster mother, Miss Edna, is growing on him. She's already raised two sons and she seems to know what makes them tick. And his teacher, Ms. Marcus, is showing him ways to put his jumbled feelings on paper. Told entirely through Lonnie's poetry, we see his heartbreak over his lost family, his thoughtful perspective on the world around him, and most of all his love for Lili and his determination to one day put at least half of their family back together. Jacqueline Woodson's poignant story of love, loss, and hope is lyrically written and enormously accessible.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51ldAvBTBCL._SX331_BO1,204,203,200_.jpg", category: "Fiction")

Book.create(title: "Broken Things", author: l_oliver, purchase_url: "https://www.amazon.com/Broken-Things-Lauren-Oliver/dp/0062224131/ref=sr_1_1?keywords=lauren+oliver&qid=1570113568&s=books&sr=1-1", description: "With all the intensity and whiplash turns of Sharp Objects and One of Us Is Lying, this engrossing psychological thriller by New York Times bestselling author Lauren Oliver is an unforgettable, mesmerizing tale of exquisite obsession, spoiled innocence, and impossible friendships. It’s been five years since Summer Marks was brutally murdered in the woods. Everyone thinks Mia and Brynn killed their best friend. That driven by their obsession with a novel called The Way into Lovelorn the three girls had imagined themselves into the magical world where their fantasies became twisted, even deadly.", image_url: "https://images-na.ssl-images-amazon.com/images/I/41KcMCm38AL._SX297_BO1,204,203,200_.jpg", category: "Thriller")

Book.create(title: "Six Of Crows", author: l_bardugo, purchase_url: "https://www.amazon.com/Six-Crows-Leigh-Bardugo/dp/125007696X/ref=sr_1_1?crid=2US34FWJ2F4EZ&keywords=six+of+crows+by+leigh+bardugo&qid=1570113794&s=books&sprefix=six+of+%2Cstripbooks%2C145&sr=1-1", description: "Ketterdam: a bustling hub of international trade where anything can be had for the right price—and no one knows that better than criminal prodigy Kaz Brekker. Kaz is offered a chance at a deadly heist that could make him rich beyond his wildest dreams. But he can’t pull it off alone.", image_url: "https://images-na.ssl-images-amazon.com/images/I/512IpKf4U3L._SX334_BO1,204,203,200_.jpg", category: "Fantasy")

Book.create(title: "Strange the Dreamer", author: l_taylor, purchase_url: "https://www.amazon.com/Strange-Dreamer-Laini-Taylor/dp/0316341673/ref=sr_1_1?crid=G7PQAQJJ9FGT&keywords=strange+the+dreamer+by+laini+taylor&qid=1570114178&s=books&sprefix=strange+the+%2Cstripbooks%2C142&sr=1-1", description: "The dream chooses the dreamer, not the other way around—and Lazlo Strange, war orphan and junior librarian, has always feared that his dream chose poorly. Since he was five years old he’s been obsessed with the mythic lost city of Weep, but it would take someone bolder than he to cross half the world in search of it. Then a stunning opportunity presents itself, in the person of a hero called the Godslayer and a band of legendary warriors, and he has to seize his chance or lose his dream forever.", image_url: "https://images-na.ssl-images-amazon.com/images/I/51n6e3ZVNrL._SX331_BO1,204,203,200_.jpg", category: "Fantasy")






